package com.functions.utils;
import com.google.common.collect.Lists;
import java.math.BigDecimal;
import java.util.Date;

import com.alibaba.fastjson.JSONObject;
import com.functions.pojo.*;
import org.junit.Test;

import static org.junit.Assert.*;

/**
 * @Author ：zbzbzzz
 * @Date ：Created in 20:27 2019/12/20
 * @Description：_____
 * @Modified By：
 * @Version: X.X
 */
public class PojoToJsonTest {
    private BaseApi baseApi;
    public PojoToJsonTest() {
       this.baseApi = new BaseApi();
       baseApi.setChannelId("testchannel");
       baseApi.setChaincodeId("zmmcode");
       baseApi.setChaincodeVersion("1.0");
       baseApi.setUserId("User1");
       baseApi.setOrgId("7258adda1803f4137eff4813e7aba323018200c5");
       baseApi.setOrgPeers("[{\"orgId\":\"7258adda1803f4137eff4813e7aba323018200c5\", \"peerDomainName\":\"peer-7258adda1803f4137eff4813e7aba323018200c5-0.peer-7258adda1803f4137eff4813e7aba323018200c5.default.svc.cluster.local\"}]");
       baseApi.setOpmethod("invoke");
       baseApi.setTimestamp("2018-10-31T17:28:16+08:00");
       baseApi.setCert("-----BEGIN CERTIFICATE-----\\nMIIDBzCCAq2gAwIBAgIQEXPZlMsReamxVtVNnKwCCzAKBggqhkjOPQQDAjCCAQQx\\nDjAMBgNVBAYTBUNISU5BMRAwDgYDVQQIEwdCRUlKSU5HMRAwDgYDVQQHEwdCRUlK\\nSU5HMXkwdwYDVQQKE3A3MjU4YWRkYTE4MDNmNDEzN2VmZjQ4MTNlN2FiYTMyMzAx\\nODIwMGM1LnBlZXItNzI1OGFkZGExODAzZjQxMzdlZmY0ODEzZTdhYmEzMjMwMTgy\\nMDBjNS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsMVMwUQYDVQQDE0pjYS5wZWVy\\nLTcyNThhZGRhMTgwM2Y0MTM3ZWZmNDgxM2U3YWJhMzIzMDE4MjAwYzUuZGVmYXVs\\ndC5zdmMuY2x1c3Rlci5sb2NhbDAeFw0xODEwMzAwMjQ5MjZaFw0yODEwMjcwMjQ5\\nMjZaMIG1MQ4wDAYDVQQGEwVDSElOQTEQMA4GA1UECBMHQkVJSklORzEQMA4GA1UE\\nBxMHQkVJSklORzF/MH0GA1UEAwx2VXNlcjFANzI1OGFkZGExODAzZjQxMzdlZmY0\\nODEzZTdhYmEzMjMwMTgyMDBjNS5wZWVyLTcyNThhZGRhMTgwM2Y0MTM3ZWZmNDgx\\nM2U3YWJhMzIzMDE4MjAwYzUuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDBZMBMG\\nByqGSM49AgEGCCqGSM49AwEHA0IABPMrzoJL/MHeSFPFOJWLqnJ0sqB0it7wDIOq\\n+eTSvvPpGk1BIDmb2n13K5V04RO8xNezDQ7I6rW4LF2elq14eH+jTTBLMA4GA1Ud\\nDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAMCsGA1UdIwQkMCKAIFBXQ5TC4acFeTlT\\nJuDZg62XkXCdnOfvbejSeKI2TXoIMAoGCCqGSM49BAMCA0gAMEUCIQCadHIKl0Mk\\nYn0WZizyDZYR4rT2q0nzjFaiW+YfV5FBjAIgNalKUe3rIwXJvXORV4ZXurEua2Ag\\nQmhcjRnVwPTjpTE=\\n-----END CERTIFICATE-----\\n");
    }

    @Test
    public void linkDateConver() {
        FinanceAssetsDebt financeAssetsDebt =new FinanceAssetsDebt();
        //region financeAssetsDebt默认值
        financeAssetsDebt.setId("");
        financeAssetsDebt.setSupplierId("");
        financeAssetsDebt.setFillDate(new Date());
        financeAssetsDebt.setA1(new BigDecimal("0"));
        financeAssetsDebt.setA2(new BigDecimal("0"));
        financeAssetsDebt.setA3(new BigDecimal("0"));
        financeAssetsDebt.setA4(new BigDecimal("0"));
        financeAssetsDebt.setA5(new BigDecimal("0"));
        financeAssetsDebt.setA6(new BigDecimal("0"));
        financeAssetsDebt.setA7(new BigDecimal("0"));
        financeAssetsDebt.setA8(new BigDecimal("0"));
        financeAssetsDebt.setA9(new BigDecimal("0"));
        financeAssetsDebt.setA10(new BigDecimal("0"));
        financeAssetsDebt.setA11(new BigDecimal("0"));
        financeAssetsDebt.setA12(new BigDecimal("0"));
        financeAssetsDebt.setA13(new BigDecimal("0"));
        financeAssetsDebt.setA14(new BigDecimal("0"));
        financeAssetsDebt.setA15(new BigDecimal("0"));
        financeAssetsDebt.setA16(new BigDecimal("0"));
        financeAssetsDebt.setA17(new BigDecimal("0"));
        financeAssetsDebt.setA18(new BigDecimal("0"));
        financeAssetsDebt.setA19(new BigDecimal("0"));
        financeAssetsDebt.setA20(new BigDecimal("0"));
        financeAssetsDebt.setA21(new BigDecimal("0"));
        financeAssetsDebt.setA22(new BigDecimal("0"));
        financeAssetsDebt.setA23(new BigDecimal("0"));
        financeAssetsDebt.setA24(new BigDecimal("0"));
        financeAssetsDebt.setA25(new BigDecimal("0"));
        financeAssetsDebt.setA26(new BigDecimal("0"));
        financeAssetsDebt.setA27(new BigDecimal("0"));
        financeAssetsDebt.setA28(new BigDecimal("0"));
        financeAssetsDebt.setA29(new BigDecimal("0"));
        financeAssetsDebt.setA30(new BigDecimal("0"));
        financeAssetsDebt.setA51(new BigDecimal("0"));
        financeAssetsDebt.setA52(new BigDecimal("0"));
        financeAssetsDebt.setA53(new BigDecimal("0"));
        financeAssetsDebt.setA54(new BigDecimal("0"));
        financeAssetsDebt.setA55(new BigDecimal("0"));
        financeAssetsDebt.setA56(new BigDecimal("0"));
        financeAssetsDebt.setA57(new BigDecimal("0"));
        financeAssetsDebt.setA58(new BigDecimal("0"));
        financeAssetsDebt.setA59(new BigDecimal("0"));
        financeAssetsDebt.setA60(new BigDecimal("0"));
        financeAssetsDebt.setA61(new BigDecimal("0"));
        financeAssetsDebt.setA62(new BigDecimal("0"));
        financeAssetsDebt.setA63(new BigDecimal("0"));
        financeAssetsDebt.setA64(new BigDecimal("0"));
        financeAssetsDebt.setA65(new BigDecimal("0"));
        financeAssetsDebt.setA66(new BigDecimal("0"));
        financeAssetsDebt.setA67(new BigDecimal("0"));
        financeAssetsDebt.setA68(new BigDecimal("0"));
        financeAssetsDebt.setA69(new BigDecimal("0"));
        financeAssetsDebt.setA70(new BigDecimal("0"));
        financeAssetsDebt.setA71(new BigDecimal("0"));
        financeAssetsDebt.setA72(new BigDecimal("0"));
        financeAssetsDebt.setA73(new BigDecimal("0"));
        financeAssetsDebt.setA74(new BigDecimal("0"));
        financeAssetsDebt.setA75(new BigDecimal("0"));
        financeAssetsDebt.setA76(new BigDecimal("0"));
        financeAssetsDebt.setA77(new BigDecimal("0"));
        financeAssetsDebt.setUpdateTime(new Date());
        financeAssetsDebt.setUpdateUser("");
        financeAssetsDebt.setUpdateUserName("");
        financeAssetsDebt.setCreateTime(new Date());
        financeAssetsDebt.setCreateUser("");
        financeAssetsDebt.setCreateUserName("");
        //endregion

        FinanceFlow financeFlow = new FinanceFlow();
        //region financeFlow默认值
        financeFlow.setId("");
        financeFlow.setSupplierId("");
        financeFlow.setFillDate(new Date());
        financeFlow.setA1(new BigDecimal("0"));
        financeFlow.setA2(new BigDecimal("0"));
        financeFlow.setA3(new BigDecimal("0"));
        financeFlow.setA4(new BigDecimal("0"));
        financeFlow.setA5(new BigDecimal("0"));
        financeFlow.setA6(new BigDecimal("0"));
        financeFlow.setA7(new BigDecimal("0"));
        financeFlow.setA8(new BigDecimal("0"));
        financeFlow.setA9(new BigDecimal("0"));
        financeFlow.setA10(new BigDecimal("0"));
        financeFlow.setA11(new BigDecimal("0"));
        financeFlow.setA12(new BigDecimal("0"));
        financeFlow.setA13(new BigDecimal("0"));
        financeFlow.setA15(new BigDecimal("0"));
        financeFlow.setA16(new BigDecimal("0"));
        financeFlow.setA18(new BigDecimal("0"));
        financeFlow.setA19(new BigDecimal("0"));
        financeFlow.setA20(new BigDecimal("0"));
        financeFlow.setA21(new BigDecimal("0"));
        financeFlow.setA22(new BigDecimal("0"));
        financeFlow.setA23(new BigDecimal("0"));
        financeFlow.setA24(new BigDecimal("0"));
        financeFlow.setA26(new BigDecimal("0"));
        financeFlow.setA27(new BigDecimal("0"));
        financeFlow.setA28(new BigDecimal("0"));
        financeFlow.setA51(new BigDecimal("0"));
        financeFlow.setA52(new BigDecimal("0"));
        financeFlow.setA53(new BigDecimal("0"));
        financeFlow.setA54(new BigDecimal("0"));
        financeFlow.setA55(new BigDecimal("0"));
        financeFlow.setA56(new BigDecimal("0"));
        financeFlow.setA57(new BigDecimal("0"));
        financeFlow.setA58(new BigDecimal("0"));
        financeFlow.setA59(new BigDecimal("0"));
        financeFlow.setA60(new BigDecimal("0"));
        financeFlow.setA61(new BigDecimal("0"));
        financeFlow.setA62(new BigDecimal("0"));
        financeFlow.setA63(new BigDecimal("0"));
        financeFlow.setA65(new BigDecimal("0"));
        financeFlow.setA66(new BigDecimal("0"));
        financeFlow.setA67(new BigDecimal("0"));
        financeFlow.setA68(new BigDecimal("0"));
        financeFlow.setA69(new BigDecimal("0"));
        financeFlow.setA72(new BigDecimal("0"));
        financeFlow.setA73(new BigDecimal("0"));
        financeFlow.setA74(new BigDecimal("0"));
        financeFlow.setA75(new BigDecimal("0"));
        financeFlow.setA77A1(new BigDecimal("0"));
        financeFlow.setA77A2(new BigDecimal("0"));
        financeFlow.setA77A3(new BigDecimal("0"));
        financeFlow.setA77A5(new BigDecimal("0"));
        financeFlow.setA77A6(new BigDecimal("0"));
        financeFlow.setA77A7(new BigDecimal("0"));
        financeFlow.setA77A8(new BigDecimal("0"));
        financeFlow.setA77A10(new BigDecimal("0"));
        financeFlow.setA77A11(new BigDecimal("0"));
        financeFlow.setA77A12(new BigDecimal("0"));
        financeFlow.setA77A13(new BigDecimal("0"));
        financeFlow.setA77A15(new BigDecimal("0"));
        financeFlow.setUpdateTime(new Date());
        financeFlow.setUpdateUser("");
        financeFlow.setUpdateUserName("");
        financeFlow.setCreateTime(new Date());
        financeFlow.setCreateUser("");
        financeFlow.setCreateUserName("");
        //endregion

        FinanceProfits financeProfits = new FinanceProfits();
        //region financeProfits默认值
        financeProfits.setId("");
        financeProfits.setSupplierId("");
        financeProfits.setFillDate(new Date());
        financeProfits.setA1(new BigDecimal("0"));
        financeProfits.setA2(new BigDecimal("0"));
        financeProfits.setA3(new BigDecimal("0"));
        financeProfits.setA4(new BigDecimal("0"));
        financeProfits.setA5(new BigDecimal("0"));
        financeProfits.setA6(new BigDecimal("0"));
        financeProfits.setA7(new BigDecimal("0"));
        financeProfits.setA8(new BigDecimal("0"));
        financeProfits.setA9(new BigDecimal("0"));
        financeProfits.setA10(new BigDecimal("0"));
        financeProfits.setA11(new BigDecimal("0"));
        financeProfits.setA12(new BigDecimal("0"));
        financeProfits.setA13(new BigDecimal("0"));
        financeProfits.setA14(new BigDecimal("0"));
        financeProfits.setA15(new BigDecimal("0"));
        financeProfits.setA16(new BigDecimal("0"));
        financeProfits.setUpdateTime(new Date());
        financeProfits.setUpdateUser("");
        financeProfits.setUpdateUserName("");
        financeProfits.setCreateTime(new Date());
        financeProfits.setCreateUser("");
        financeProfits.setCreateUserName("");
        //endregion

        FinanceSimple financeSimple = new FinanceSimple();
        //region financeSimple默认值
        financeSimple.setId("");
        financeSimple.setSupplierId("");
        financeSimple.setFillDate(new Date());
        financeSimple.setA1("");
        financeSimple.setB1(new BigDecimal("0"));
        financeSimple.setC1("");
        financeSimple.setD1("");
        financeSimple.setA2("");
        financeSimple.setB2(new BigDecimal("0"));
        financeSimple.setC2("");
        financeSimple.setD2("");
        financeSimple.setA3("");
        financeSimple.setB3(new BigDecimal("0"));
        financeSimple.setC3("");
        financeSimple.setD3("");
        financeSimple.setA4("");
        financeSimple.setB4(new BigDecimal("0"));
        financeSimple.setC4("");
        financeSimple.setD4("");
        financeSimple.setA5("");
        financeSimple.setB5(new BigDecimal("0"));
        financeSimple.setC5("");
        financeSimple.setD5("");
        financeSimple.setA6("");
        financeSimple.setB6(new BigDecimal("0"));
        financeSimple.setC6("");
        financeSimple.setD6("");
        financeSimple.setA7("");
        financeSimple.setB7(new BigDecimal("0"));
        financeSimple.setC7("");
        financeSimple.setD7("");
        financeSimple.setA8("");
        financeSimple.setB8(new BigDecimal("0"));
        financeSimple.setC8("");
        financeSimple.setD8("");
        financeSimple.setA9("");
        financeSimple.setB9(new BigDecimal("0"));
        financeSimple.setC9("");
        financeSimple.setD9("");
        financeSimple.setA10("");
        financeSimple.setB10(new BigDecimal("0"));
        financeSimple.setC10("");
        financeSimple.setD10("");
        financeSimple.setA11("");
        financeSimple.setB11(new BigDecimal("0"));
        financeSimple.setC11("");
        financeSimple.setD11("");
        financeSimple.setA12("");
        financeSimple.setB12(new BigDecimal("0"));
        financeSimple.setC12("");
        financeSimple.setD12("");
        financeSimple.setA13("");
        financeSimple.setB13(new BigDecimal("0"));
        financeSimple.setC13("");
        financeSimple.setD13("");
        financeSimple.setA14("");
        financeSimple.setB14(new BigDecimal("0"));
        financeSimple.setC41("");
        financeSimple.setD14("");
        financeSimple.setA15("");
        financeSimple.setB15(new BigDecimal("0"));
        financeSimple.setC15("");
        financeSimple.setD15("");
        financeSimple.setA16("");
        financeSimple.setB16(new BigDecimal("0"));
        financeSimple.setD16("");
        financeSimple.setA17("");
        financeSimple.setB17(new BigDecimal("0"));
        financeSimple.setC17("");
        financeSimple.setD17("");
        financeSimple.setA18("");
        financeSimple.setB18(new BigDecimal("0"));
        financeSimple.setC18("");
        financeSimple.setD18("");
        financeSimple.setA19("");
        financeSimple.setB19(new BigDecimal("0"));
        financeSimple.setC19("");
        financeSimple.setD19("");
        financeSimple.setA20("");
        financeSimple.setB20(new BigDecimal("0"));
        financeSimple.setC20("");
        financeSimple.setD20("");
        financeSimple.setA21("");
        financeSimple.setB21(new BigDecimal("0"));
        financeSimple.setC21("");
        financeSimple.setD21("");
        financeSimple.setA22("");
        financeSimple.setB22(new BigDecimal("0"));
        financeSimple.setC22("");
        financeSimple.setD22("");
        financeSimple.setA23("");
        financeSimple.setB23(new BigDecimal("0"));
        financeSimple.setC23("");
        financeSimple.setD23("");
        financeSimple.setA24("");
        financeSimple.setB24(new BigDecimal("0"));
        financeSimple.setC24("");
        financeSimple.setD24("");
        financeSimple.setA25("");
        financeSimple.setB25(new BigDecimal("0"));
        financeSimple.setC25("");
        financeSimple.setD25("");
        financeSimple.setA26("");
        financeSimple.setB26(new BigDecimal("0"));
        financeSimple.setC26("");
        financeSimple.setD26("");
        financeSimple.setA27("");
        financeSimple.setB27(new BigDecimal("0"));
        financeSimple.setC27("");
        financeSimple.setD27("");
        financeSimple.setA28("");
        financeSimple.setB28(new BigDecimal("0"));
        financeSimple.setC28("");
        financeSimple.setD28("");
        financeSimple.setA29("");
        financeSimple.setB29(new BigDecimal("0"));
        financeSimple.setC29("");
        financeSimple.setD29("");
        financeSimple.setA30("");
        financeSimple.setB30(new BigDecimal("0"));
        financeSimple.setC30("");
        financeSimple.setD30("");
        financeSimple.setA31("");
        financeSimple.setB31(new BigDecimal("0"));
        financeSimple.setC31("");
        financeSimple.setD31("");
        financeSimple.setA32("");
        financeSimple.setB32(new BigDecimal("0"));
        financeSimple.setC32("");
        financeSimple.setD32("");
        financeSimple.setA33("");
        financeSimple.setB33(new BigDecimal("0"));
        financeSimple.setC33("");
        financeSimple.setD33("");
        financeSimple.setA34("");
        financeSimple.setB34(new BigDecimal("0"));
        financeSimple.setC34("");
        financeSimple.setD34("");
        financeSimple.setUpdateTime(new Date());
        financeSimple.setUpdateUser("");
        financeSimple.setUpdateUserName("");
        financeSimple.setCreateTime(new Date());
        financeSimple.setCreateUser("");
        financeSimple.setCreateUserName("");
        //endregion

        JSONObject jsonObject=PojoToJson.linkDateConver(financeAssetsDebt,financeFlow,financeProfits,financeSimple);
        System.out.println(jsonObject);
    }



    @Test
    public void financeAssetsDebtConver() {
        FinanceAssetsDebt financeAssetsDebt =new FinanceAssetsDebt();
        //region financeAssetsDebt默认值
        financeAssetsDebt.setId("");
        financeAssetsDebt.setSupplierId("");
        financeAssetsDebt.setFillDate(new Date());
        financeAssetsDebt.setA1(new BigDecimal("0"));
        financeAssetsDebt.setA2(new BigDecimal("0"));
        financeAssetsDebt.setA3(new BigDecimal("0"));
        financeAssetsDebt.setA4(new BigDecimal("0"));
        financeAssetsDebt.setA5(new BigDecimal("0"));
        financeAssetsDebt.setA6(new BigDecimal("0"));
        financeAssetsDebt.setA7(new BigDecimal("0"));
        financeAssetsDebt.setA8(new BigDecimal("0"));
        financeAssetsDebt.setA9(new BigDecimal("0"));
        financeAssetsDebt.setA10(new BigDecimal("0"));
        financeAssetsDebt.setA11(new BigDecimal("0"));
        financeAssetsDebt.setA12(new BigDecimal("0"));
        financeAssetsDebt.setA13(new BigDecimal("0"));
        financeAssetsDebt.setA14(new BigDecimal("0"));
        financeAssetsDebt.setA15(new BigDecimal("0"));
        financeAssetsDebt.setA16(new BigDecimal("0"));
        financeAssetsDebt.setA17(new BigDecimal("0"));
        financeAssetsDebt.setA18(new BigDecimal("0"));
        financeAssetsDebt.setA19(new BigDecimal("0"));
        financeAssetsDebt.setA20(new BigDecimal("0"));
        financeAssetsDebt.setA21(new BigDecimal("0"));
        financeAssetsDebt.setA22(new BigDecimal("0"));
        financeAssetsDebt.setA23(new BigDecimal("0"));
        financeAssetsDebt.setA24(new BigDecimal("0"));
        financeAssetsDebt.setA25(new BigDecimal("0"));
        financeAssetsDebt.setA26(new BigDecimal("0"));
        financeAssetsDebt.setA27(new BigDecimal("0"));
        financeAssetsDebt.setA28(new BigDecimal("0"));
        financeAssetsDebt.setA29(new BigDecimal("0"));
        financeAssetsDebt.setA30(new BigDecimal("0"));
        financeAssetsDebt.setA51(new BigDecimal("0"));
        financeAssetsDebt.setA52(new BigDecimal("0"));
        financeAssetsDebt.setA53(new BigDecimal("0"));
        financeAssetsDebt.setA54(new BigDecimal("0"));
        financeAssetsDebt.setA55(new BigDecimal("0"));
        financeAssetsDebt.setA56(new BigDecimal("0"));
        financeAssetsDebt.setA57(new BigDecimal("0"));
        financeAssetsDebt.setA58(new BigDecimal("0"));
        financeAssetsDebt.setA59(new BigDecimal("0"));
        financeAssetsDebt.setA60(new BigDecimal("0"));
        financeAssetsDebt.setA61(new BigDecimal("0"));
        financeAssetsDebt.setA62(new BigDecimal("0"));
        financeAssetsDebt.setA63(new BigDecimal("0"));
        financeAssetsDebt.setA64(new BigDecimal("0"));
        financeAssetsDebt.setA65(new BigDecimal("0"));
        financeAssetsDebt.setA66(new BigDecimal("0"));
        financeAssetsDebt.setA67(new BigDecimal("0"));
        financeAssetsDebt.setA68(new BigDecimal("0"));
        financeAssetsDebt.setA69(new BigDecimal("0"));
        financeAssetsDebt.setA70(new BigDecimal("0"));
        financeAssetsDebt.setA71(new BigDecimal("0"));
        financeAssetsDebt.setA72(new BigDecimal("0"));
        financeAssetsDebt.setA73(new BigDecimal("0"));
        financeAssetsDebt.setA74(new BigDecimal("0"));
        financeAssetsDebt.setA75(new BigDecimal("0"));
        financeAssetsDebt.setA76(new BigDecimal("0"));
        financeAssetsDebt.setA77(new BigDecimal("0"));
        financeAssetsDebt.setUpdateTime(new Date());
        financeAssetsDebt.setUpdateUser("");
        financeAssetsDebt.setUpdateUserName("");
        financeAssetsDebt.setCreateTime(new Date());
        financeAssetsDebt.setCreateUser("");
        financeAssetsDebt.setCreateUserName("");
        //endregion
        PojoToJson pojoToJson = new PojoToJson();
        System.out.println(pojoToJson.FinanceAssetsDebtConver(financeAssetsDebt));
    }



    // 通用方法test
    @Test
    public void testLinkDateConver() {
        FinanceAssetsDebt financeAssetsDebt =new FinanceAssetsDebt();
        //region financeAssetsDebt默认值
        financeAssetsDebt.setId("");
        financeAssetsDebt.setSupplierId("");
        financeAssetsDebt.setFillDate(new Date());
        financeAssetsDebt.setA1(new BigDecimal("0"));
        financeAssetsDebt.setA2(new BigDecimal("0"));
        financeAssetsDebt.setA3(new BigDecimal("0"));
        financeAssetsDebt.setA4(new BigDecimal("0"));
        financeAssetsDebt.setA5(new BigDecimal("0"));
        financeAssetsDebt.setA6(new BigDecimal("0"));
        financeAssetsDebt.setA7(new BigDecimal("0"));
        financeAssetsDebt.setA8(new BigDecimal("0"));
        financeAssetsDebt.setA9(new BigDecimal("0"));
        financeAssetsDebt.setA10(new BigDecimal("0"));
        financeAssetsDebt.setA11(new BigDecimal("0"));
        financeAssetsDebt.setA12(new BigDecimal("0"));
        financeAssetsDebt.setA13(new BigDecimal("0"));
        financeAssetsDebt.setA14(new BigDecimal("0"));
        financeAssetsDebt.setA15(new BigDecimal("0"));
        financeAssetsDebt.setA16(new BigDecimal("0"));
        financeAssetsDebt.setA17(new BigDecimal("0"));
        financeAssetsDebt.setA18(new BigDecimal("0"));
        financeAssetsDebt.setA19(new BigDecimal("0"));
        financeAssetsDebt.setA20(new BigDecimal("0"));
        financeAssetsDebt.setA21(new BigDecimal("0"));
        financeAssetsDebt.setA22(new BigDecimal("0"));
        financeAssetsDebt.setA23(new BigDecimal("0"));
        financeAssetsDebt.setA24(new BigDecimal("0"));
        financeAssetsDebt.setA25(new BigDecimal("0"));
        financeAssetsDebt.setA26(new BigDecimal("0"));
        financeAssetsDebt.setA27(new BigDecimal("0"));
        financeAssetsDebt.setA28(new BigDecimal("0"));
        financeAssetsDebt.setA29(new BigDecimal("0"));
        financeAssetsDebt.setA30(new BigDecimal("0"));
        financeAssetsDebt.setA51(new BigDecimal("0"));
        financeAssetsDebt.setA52(new BigDecimal("0"));
        financeAssetsDebt.setA53(new BigDecimal("0"));
        financeAssetsDebt.setA54(new BigDecimal("0"));
        financeAssetsDebt.setA55(new BigDecimal("0"));
        financeAssetsDebt.setA56(new BigDecimal("0"));
        financeAssetsDebt.setA57(new BigDecimal("0"));
        financeAssetsDebt.setA58(new BigDecimal("0"));
        financeAssetsDebt.setA59(new BigDecimal("0"));
        financeAssetsDebt.setA60(new BigDecimal("0"));
        financeAssetsDebt.setA61(new BigDecimal("0"));
        financeAssetsDebt.setA62(new BigDecimal("0"));
        financeAssetsDebt.setA63(new BigDecimal("0"));
        financeAssetsDebt.setA64(new BigDecimal("0"));
        financeAssetsDebt.setA65(new BigDecimal("0"));
        financeAssetsDebt.setA66(new BigDecimal("0"));
        financeAssetsDebt.setA67(new BigDecimal("0"));
        financeAssetsDebt.setA68(new BigDecimal("0"));
        financeAssetsDebt.setA69(new BigDecimal("0"));
        financeAssetsDebt.setA70(new BigDecimal("0"));
        financeAssetsDebt.setA71(new BigDecimal("0"));
        financeAssetsDebt.setA72(new BigDecimal("0"));
        financeAssetsDebt.setA73(new BigDecimal("0"));
        financeAssetsDebt.setA74(new BigDecimal("0"));
        financeAssetsDebt.setA75(new BigDecimal("0"));
        financeAssetsDebt.setA76(new BigDecimal("0"));
        financeAssetsDebt.setA77(new BigDecimal("0"));
        financeAssetsDebt.setUpdateTime(new Date());
        financeAssetsDebt.setUpdateUser("");
        financeAssetsDebt.setUpdateUserName("");
        financeAssetsDebt.setCreateTime(new Date());
        financeAssetsDebt.setCreateUser("");
        financeAssetsDebt.setCreateUserName("");
        //endregion
        PojoToJson pojoToJson = new PojoToJson();
        System.out.println(pojoToJson.linkDateConver(financeAssetsDebt));
    }


}